name: flutterandroidprinter_example
description: Demonstrates how to use the flutterandroidprinter plugin.
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutterandroidprinter:
    path: ../
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/rabbit_black.jpg
